[package]
name = "hr-monitor"
version = "0.2.0"
edition = "2024"
authors = ["kanggui <kg.he@outlook.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
bluest = "0.6"
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
camino = "1"

